### ISSUE TITLE
analogDifferential 11 bits only?

### ISSUE THREAD

**Issue by LowPowerLab** [Molorius/ATSAMD21-ADC#1]
I'm not quite clear if this is a bug or if I'm missing something here, any help to get to the bottom of this would be great.

Is there any way to obtain a true 12bit differential result using `analogDifferential()`?

For instance if we do a single ended analogRead of a 3V input the 12bit ADC result is the expected ~3720 (of a max 4095).
Simply switching `ADC->CTRLB.reg` to `CTRL DIFFMODE` and setting the MUXPOS/MUXNEGs, then applying 3V of difference between these differential inputs, produce half of the expected value. The reference is unchanged in both cases and is the default `analogReference(AR_DEFAULT)` which should be 3.3V. If I change the reference to not do a DIV2 then the result saturates to 2047 (11bit).

In [this Arduino forum post](https://forum.arduino.cc/index.php?topic=465938.msg3206760#msg3206760) you seem to suggest the true 12bit value in differential reads is still available but I could not find a way to obtain it. Or maybe differential mode shifts the reference to half of whatever it is set to, and then yields a **signed** 12bit  (11bits + 1 sign bit) result from that? That would seem quite wrong.

**Comment by Molorius** [comment]
Datasheet section 32.6.5:
> The ADC has two conversion options: differential and single-ended. When measuring signals where the positive input is always at a higher voltage than the negative input, the single-ended conversion should be used in order to have full 12-bit resolution in the conversion, which has only positive values. The negative input must be connected to ground. This ground could be the internal GND, IOGND or an external ground connected to a pin. Refer to INPUTCTRL for selection details. If the positive input may go below the negative input, creating some negative results, the differential mode should be used in order to get correct results. The configuration of the conversion is done in the Differential Mode bit in the Control B register (CTRLB.DIFFMODE). These two types of conversion could be run in single mode or in free-running mode. When set up in free-running mode, an ADC input will continuously sample and do new conversions. The INTFLAG.RESRDY bit will be set at the end of each conversion.

The part we're most interested in:
> the single-ended conversion should be used in order to have full 12-bit resolution in the conversion, which has only positive values. The negative input must be connected to ground.

So no, a max value of 1<sup>12</sup> is not possible when using 2 pins, unless one of those pins is connected to ground. 

My forum post you found points to the fact that a signed result with a max of 1<sup>11</sup> is still twelve bits of information, but one of the bits is used to determine the sign. I'm not sure of the exact mechanism that this cpu does to return the signed value, but it is indeed quite right. 

That being said, I have not tested returning an unsigned result with 2 ungrounded pins. The datasheet may just have that as a warning to avoid being at fault if something happens. Know that it may cause damage to the adc or other parts of the microcontroller. I do not have one I am willing to test it on.

**Comment by LowPowerLab** [comment]
I appreciate your response, thank you.

Understood, it's an implied limitation, which does make sense, but it's not obvious or pointed out in the datasheet. I think it could have been implemented a little better

Meanwhile I did more experimenting and what ends up happening is to get true 12 bit in a differential approach (have the MCU do the difference rather than you take 2 ADC samples of the 2 pins and manually subtract them) you have to just set the MUXNEG to the other pin instead of GND and switch OFF the differential mode (ie single ended). The only downside is you cannot have MUXPOS go negative (if it does, the result is simply clamped at 0). But this is OK if the MUXPOS is always expected to be positive WRT MUXNEG.
